from enum import Enum

class MyEnum(Enum):

	def __str__(self):
		return "({0}={1})".format(self.__class__.__name__, self.name)

class RoomRequest(MyEnum):
	GET_ROOMATES = 'GET_ROOMATES'
	GET_ROOMS = 'GET_ROOMS'
	CREATE_A_ROOM = 'CREATE_A_ROOM'
	JOIN_ROOM = 'JOIN_ROOM'
	START_GAME = 'START_GAME'
	LEAVE_ROOM = 'LEAVE_ROOM'

class RoomGameState(MyEnum):
	STOPPED = 'STOPPED'
	STARTED = 'STARTED'
	PAUSED = 'PAUSED'

class RoomGameStatus(MyEnum):
	ARE_ROOMATES_IN_GAME = 'ARE_ROOMATES_IN_GAME'
	GAME_MESSAGE = 'GAME_MESSAGE'
	GAME_CAN_BE_STARTED = 'GAME_CAN_BE_STARTED'
	GAME_HAS_STARTED = 'GAME_HAS_STARTED'
	ASK_FOR_ROOMATES = 'ASK_FOR_ROOMATES'
	GAME_NOT_STARTED = 'GAME_NOT_STARTED'

class ClientRcvMessage(MyEnum):
	GET_ROOMATES_REP = 'GET_ROOMATES_REP'
	GET_ROOMS_REP = 'GET_ROOMS_REP'
	GAME_MESSAGE_REP = 'GAME_MESSAGE_REP'
	CREATE_A_ROOM_REP = 'CREATE_A_ROOM_REP'
	JOIN_ROOM_REP = 'JOIN_ROOM_REP'
	START_GAME_REP = 'START_GAME_REP'
	LEAVE_ROOM_REP = 'LEAVE_ROOM_REP'
	PLAYER_JOINED_GAME = 'PLAYER_JOINED_GAME'
	ARE_ROOMATES_IN_GAME_REP = 'ARE_ROOMATES_IN_GAME_REP'
	GAME_CAN_BE_STARTED_REP = 'GAME_CAN_BE_STARTED_REP'
	GAME_HAS_STARTED_REP = 'GAME_HAS_STARTED_REP'
	GAME_HAS_ALREADY_STARTED_REP = 'GAME_HAS_ALREADY_STARTED_REP'
	ASK_FOR_ROOMATES_REP = 'ASK_FOR_ROOMATES_REP'
