from enum import Enum

class MyEnum(Enum):

	def __str__(self):
		return "({0}={1})".format(self.__class__.__name__, self.name)

class RoomRequest(MyEnum):
	GET_ROOMATES = 'GET_ROOMATES'
	GET_ROOMS = 'GET_ROOMS'
	CREATE_A_ROOM = 'CREATE_A_ROOM'
	JOIN_ROOM = 'JOIN_ROOM'
	START_GAME = 'START_GAME'
	LEAVE_ROOM = 'LEAVE_ROOM'
	GET_CURRENT_PLAYER = 'GET_CURRENT_PLAYER'
	SET_FIRST_PLAYER = 'SET_FIRST_PLAYER'

class RoomGameState(MyEnum):
	STOPPED = 'STOPPED'
	STARTED = 'STARTED'
	PAUSED = 'PAUSED'

class RoomStatus(MyEnum):
	OPEN = 'OPEN'
	FULL = 'FULL'
	CLOSED = 'CLOSED'
	GAME_IS_STARTING = 'GAME_HAS_STARTED'

class RoomGameStatus(MyEnum):
	ARE_ROOMATES_IN_GAME = 'ARE_ROOMATES_IN_GAME'
	GAME_MESSAGE = 'GAME_MESSAGE'
	GAME_CAN_BE_STARTED = 'GAME_CAN_BE_STARTED'
	GAME_HAS_STARTED = 'GAME_HAS_STARTED'
	ASK_FOR_ROOMATES = 'ASK_FOR_ROOMATES'
	GAME_NOT_STARTED = 'GAME_NOT_STARTED'
	DOCUMENTATION = 'DOCUMENTATION'
	OPEN_GAME_CONN = 'OPEN_GAME_CONN'
	STOP_GAME = 'STOP_GAME'

class GameMoveType(MyEnum):
	PICK_OPTION = 'PICK_OPTION' # pick an option between a set of options
	PICK_CARDS = 'PICK_CARDS'
	PICK_ONE = 'PICK_ONE'
	PICK_TWO = 'PICK_TWO'   
	DATATYPE_INT = 'DATATYPE_INT'
	DATATYPE_STR = 'DATATYPE_STR'
	DATATYPE_CARDS = 'DATATYPE_CARDS'

class LoopChoices(MyEnum):
	PRETTY_HELP = 'h'
	CMD_RULES = 'r'
	PLAY_ROUND = 'p'
	LEAVE_GAME = 'q'
	JOIN_ROOM = 'j'
	CREATE_ROOM = 'c'

class ClientRcvMsg(MyEnum):
	GET_ROOMATES_REP = 'GET_ROOMATES_REP'
	GET_ROOMS_REP = 'GET_ROOMS_REP'
	GET_CURRENT_PLAYER_REP = 'GET_CURRENT_PLAYER_REP'
	SET_FIRST_PLAYER_REP = 'SET_FIRST_PLAYER_REP'
	GAME_MESSAGE_REP = 'GAME_MESSAGE_REP'
	CREATE_A_ROOM_REP = 'CREATE_A_ROOM_REP'
	JOIN_ROOM_REP = 'JOIN_ROOM_REP'
	START_GAME_REP = 'START_GAME_REP'
	LEAVE_ROOM_REP = 'LEAVE_ROOM_REP'
	PLAYER_JOINED_GAME = 'PLAYER_JOINED_GAME'
	ARE_ROOMATES_IN_GAME_REP = 'ARE_ROOMATES_IN_GAME_REP'
	GAME_CAN_BE_STARTED_REP = 'GAME_CAN_BE_STARTED_REP'
	GAME_HAS_STARTED_REP = 'GAME_HAS_STARTED_REP'
	GAME_HAS_ALREADY_STARTED_REP = 'GAME_HAS_ALREADY_STARTED_REP'
	ASK_FOR_ROOMATES_REP = 'ASK_FOR_ROOMATES_REP'
	ERROR='ERROR'
	OPEN_GAME_CONN_REP = 'OPEN_GAME_CONN_REP'

class GameServerMsg(MyEnum):
	PLAY_MOVE = 'PLAY_MOVE'
	START_GAME = 'START_GAME'
	GET_GAME_STATUS = 'GET_GAME_STATUS'
	PAUSE_GAME = 'PAUSE_GAME'
	INITIAL_PLAYER_SET = 'INITIAL_PLAYER_SET'
	MOVE_PLAYED = 'MOVE_PLAYED'
	SET_INITIAL_PLAYER = 'SET_INITIAL_PLAYER'

